# Generated by Django 4.2.2 on 2023-06-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_is_active_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
