# Generated by Django 4.2.2 on 2023-06-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_remove_destination_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
